language: python

python:
  - 2.7

before_install:
  - pip install codecov nose2 nose2-cov

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - nose2 -F -C -v

after_success:
  - codecov
