FROM python:3.6

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg2 \
        software-properties-common \
        curl \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add - \
    && add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
           $(lsb_release -cs) \
           stable" \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        docker-ce \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV TEST_DIRECTORY=/irobot
RUN mkdir -p "${TEST_DIRECTORY}"
WORKDIR "${TEST_DIRECTORY}"
ADD . .

RUN pip install --disable-pip-version-check -r requirements.txt \
    && pip install --disable-pip-version-check -r requirements-test.txt \
    && pip install --disable-pip-version-check codecov nose2 nose2-cov

CMD ["nose2", "-C", "--coverage-report", "term-missing", "-v"]
